### ISSUE TITLE
Issue with teleporting to other maps while doing collectables

### ISSUE THREAD

**Issue by Luysita** [FFXIV-CombatReborn/GatherBuddyReborn#240]
Hello been having this issue after teleporting after 3 or 4 maps

https://imgur.com/9vppXsA

Only way to fix it is using Return or retart the game.

Error log:

17:42:38.004 | WRN | [GatherbuddyReborn] Task <MoveToTerritory>b__93_4 took too long to execute
	   at ECommons.Automation.LegacyTaskManager.TaskManager.Tick(Object _) in D:\a\GatherBuddyReborn\GatherBuddyReborn\ECommons\ECommons\Automation\LegacyTaskManager\TaskManager.cs:line 160
17:42:50.030 | WRN | [GatherbuddyReborn] Task <MoveToTerritory>b__93_4 took too long to execute
	   at ECommons.Automation.LegacyTaskManager.TaskManager.Tick(Object _) in D:\a\GatherBuddyReborn\GatherBuddyReborn\ECommons\ECommons\Automation\LegacyTaskManager\TaskManager.cs:line 160
17:43:02.011 | WRN | [GatherbuddyReborn] Task <MoveToTerritory>b__93_4 took too long to execute
	   at ECommons.Automation.LegacyTaskManager.TaskManager.Tick(Object _) in D:\a\GatherBuddyReborn\GatherBuddyReborn\ECommons\ECommons\Automation\LegacyTaskManager\TaskManager.cs:line 160
17:43:14.020 | WRN | [GatherbuddyReborn] Task <MoveToTerritory>b__93_4 took too long to execute
	   at ECommons.Automation.LegacyTaskManager.TaskManager.Tick(Object _) in D:\a\GatherBuddyReborn\GatherBuddyReborn\ECommons\ECommons\Automation\LegacyTaskManager\TaskManager.cs:line 160

**Comment by lazyranma** [comment]
This usually happens when two plugins try to teleport at the same time, or some plugins tries to teleport too often. Or may be some other bug is involved.
This log shows only that teleporting does not work at all.

**Comment by Luysita** [comment]
I was only using Gather Buddy at the time. But either way seems fixed after the update since it's not doing it anymore, thank you
